/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATableColumn: typeof import('ant-design-vue/es')['TableColumn']
    ATag: typeof import('ant-design-vue/es')['Tag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AAvatar: typeof import('ant-design-vue/es')['Avatar']
  const AButton: typeof import('ant-design-vue/es')['Button']
  const AInput: typeof import('ant-design-vue/es')['Input']
  const ALayout: typeof import('ant-design-vue/es')['Layout']
  const ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
  const ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
  const ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
  const AMenu: typeof import('ant-design-vue/es')['Menu']
  const AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
  const APagination: typeof import('ant-design-vue/es')['Pagination']
  const ASelect: typeof import('ant-design-vue/es')['Select']
  const ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
  const ATable: typeof import('ant-design-vue/es')['Table']
  const ATableColumn: typeof import('ant-design-vue/es')['TableColumn']
  const ATag: typeof import('ant-design-vue/es')['Tag']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}