/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AQrcode: typeof import('ant-design-vue/es')['QRCode']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AAlert: typeof import('ant-design-vue/es')['Alert']
  const ABackTop: typeof import('ant-design-vue/es')['BackTop']
  const ABadge: typeof import('ant-design-vue/es')['Badge']
  const AButton: typeof import('ant-design-vue/es')['Button']
  const ACard: typeof import('ant-design-vue/es')['Card']
  const ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
  const ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
  const AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
  const ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
  const ADivider: typeof import('ant-design-vue/es')['Divider']
  const ADropdown: typeof import('ant-design-vue/es')['Dropdown']
  const AForm: typeof import('ant-design-vue/es')['Form']
  const AFormItem: typeof import('ant-design-vue/es')['FormItem']
  const AInput: typeof import('ant-design-vue/es')['Input']
  const AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
  const ALayout: typeof import('ant-design-vue/es')['Layout']
  const ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
  const ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
  const AMenu: typeof import('ant-design-vue/es')['Menu']
  const AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
  const AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
  const AQrcode: typeof import('ant-design-vue/es')['QRCode']
  const ARadio: typeof import('ant-design-vue/es')['Radio']
  const ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
  const AResult: typeof import('ant-design-vue/es')['Result']
  const ASelect: typeof import('ant-design-vue/es')['Select']
  const ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
  const ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
  const ASwitch: typeof import('ant-design-vue/es')['Switch']
  const ATabPane: typeof import('ant-design-vue/es')['TabPane']
  const ATabs: typeof import('ant-design-vue/es')['Tabs']
  const ATextarea: typeof import('ant-design-vue/es')['Textarea']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}